### ISSUE TITLE
File dedup

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/gooi#22]
Random thought, would be cool to have.

**Comment by tomsmeding** [comment]
Client-side (i.e. within one upload) or server-side (i.e. whole uploads)?
Server-side is mostly useful for your usecase I guess, when the exporation
time is ∞ :p

**Comment by tomsmeding** [comment]
@lieuwex as a benchmark what does the following give in your gooi server files directory?

    sha1sum * | cut -d' ' -f1 | sort | uniq -c | awk '{print $1}'  | sort -rn | uniq -c

**Comment by lieuwex** [comment]
@tomsmeding sorry for late reply

```
      1 8
      3 4
      1 3
     48 2
    984 1
```

**Comment by tomsmeding** [comment]
Apparently that command worked without testing :p

Okay, so dedup would save you 1*7+3*3+1*2+48*1 = 66 files, which is 6% of the total number of files you have. That's actually pretty significant, wouldn't have expected it to be that much. Why are you re-uploading stuff? :P

Would the second upload just return the first upload's ID, or should it generate new ID's for the duplicate uploads?

**Comment by lieuwex** [comment]
First I thought that returning the original ID would be the best option, but that will not work nicely with lsgooi I guess.

So maybe getting a new ID and symlinking the file to the old one could do it, but that would break the expiration stuff. So I don't know actually.

**Comment by lieuwex** [comment]
Hardlinks!

**Comment by tomsmeding** [comment]
you're not serious are you?

**Comment by tomsmeding** [comment]
From #26:

> For the record you consider this out of scope for gooi, because this can be handled in btrfs — not that any of us have that on their gooi instances, but you have experience using it and you were going to be the consumer anyway. :)

> For me, I like that we retain gooi's simplicity.
