### ISSUE TITLE
Supporting .netrc

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/gooi#23]
I want to put `/gooi` behind a basic auth wall, but that will currently break the gooi client of course.
It is a possibility to add netrc support in a way that [curl does](https://ec.haxx.se/usingcurl/usingcurl-netrc). But I'm actually not that convinced myself. So I'm just basically creating this issue for discussion purposes.

Another option would be to create a authgooi client fork for myself that adds a basic auth netrc layer, since the code required for the client [is small](https://github.com/tomsmeding/gooi/blob/6077fd396a7106e377964cad73d1d4a0497cfb0e/client/bin/gooi.js). But that still would require to add basic auth support in the library itself. ([see the auth field on http(s) options of node](https://nodejs.org/api/http.html#http_http_request_url_options_callback))

**Comment by tomsmeding** [comment]
Since the hostname to connect to is given in the config file, shouldn't the user:pass thing not also be in there? Or do you perhaps want to put special security measures on the netrc file?

**Comment by tomsmeding** [comment]
If you really want a netrc file, would the `basicauth` branch work?

**Comment by lieuwex** [comment]
b2d835e6e2d5b8e34fd2473f33cf9d3dcb4b566f
