### ISSUE TITLE
Auto-zipping multifile uploads

### ISSUE THREAD

**Issue by tomsmeding** [tomsmeding/gooi#3]
Feature to zip all given files and upload as one

**Comment by lieuwex** [comment]
https://www.npmjs.com/package/yazl or https://www.npmjs.com/package/zip-stream have nice stream zipping wrappers.

**Comment by tomsmeding** [comment]
Given that #6 exists, I think that this is at least implemented now

**Comment by lieuwex** [comment]
There still are debug messages though
