### ISSUE TITLE
Option to change the name of the produced zip file

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/gooi#6]
-n and --name for example?

**Comment by tomsmeding** [comment]
What if the argument after -n doesn't include ".zip"?

**Comment by lieuwex** [comment]
I guess we want to append '.zip' then.

**Comment by tomsmeding** [comment]
how is https://github.com/tomsmeding/gooi/tree/uploadname?

**Comment by tomsmeding** [comment]
Done in 057bed1e1a31df7eaf8bf521c5857ece30c83dac :)
